### ISSUE TITLE
Investigación de tecnologías

### ISSUE THREAD

**Issue by robperch** [santibatte/dpa_2021#11]
## Asignación tecnologías - Propuesta Rob
1. Santi:
    - Líder: Flask, Luigi
    - Backup: S3, PostgreSQL, Pandas/Koalas/PySpark
2. Mariana
    - Líder: PostgreSQL, S3
    - Backup: Dash, Pandas/Koalas/PySpark
3. Rob
    - Líder: Marbles, Zeppelin
    - Backup: Luigi, Sklearn/MLlib (Spark), Pandas/Koalas/PySpark
4. Carlos
    - Líder: Dash, Sklearn/MLlib (Spark)
    - Backup: Zeppelin, Flask, Pandas/Koalas/PySpark

Elegir tecnologías para investigarlas. Cada quien deberá anotar su nombre en la sección de *interesados* para que veamos como distribuimos el trabajo. (Elegir máximo 3)
## Elección tecnologías
- Luigi: Orquestador de jobs
    - Interesados:  Rob, Santi, Mariana
- Pandas/Koalas/PySpark: Procesamiento de datos
    - Interesados: Carlos, Mariana 
- Marbles: Pruebas unitarias a datos
    - Interesados: Rob
- S3: Servicio de alamacenamiento de AWS
    - Interesados: Santi, Mariana
- PostgreSQL: Base de datos
    - Interesados: Santi, Mariana
- Sklearn/MLlib (Spark): Machine learning
    - Interesados: Carlos, Mariana
- Zeppelin: Notebooks en la nube
    - Interesados: Rob, Carlos
- Flask: Desarrollo de API REST
    - Interesados: Santi
- Dash Plotly: Dashboards
    - Interesados: Carlos, Mariana

**Comment by santibatte** [comment]
Cierro este issue porque ya está resuleto de acuerdo a la propuesta de Rober.
