### ISSUE TITLE
Requirements.txt update

### ISSUE THREAD

**Issue by codeMariana** [santibatte/dpa_2021#15]
Actualizar `requirements.txt` con las librerías nuevas requeridas.

- [x] Instalar el paquete SODAP (actualizar tu requirements.txt),  
- [x] Instalar el paquete boto3 (actualizar tu requirements.txt).
- [x] Instalar PyYAML (actualizar tu requirements.txt).
- [x] instalar pickle

**Comment by santibatte** [comment]
una pregunta, una vez que se actualicen los requirements, como hacemos para que se actualice nuestro ambiente local ? se le da pip install requirements.txt o pip update o algo asi ? Lo vemos en la reunión igual pero voy anotando algunas dudas que me surgieron por acá.

**Comment by santibatte** [comment]
Modifiqué este issue para que solo sea lo de hacer el update del requirements.txt

**Comment by santibatte** [comment]
Cree rama issue_15 y agregue boto3 a los requirements. 
También agregué pickle-mixin para tener pickles (no sé si esto es correcto o si ya lo teníamos con otra librería instalada en los requirements anteriormente). 

Falta agregar SODAP que todavía no sé exactamente cómo se instala.

**Comment by santibatte** [comment]
PyYaml ya estaba instalado por ustedes.
