### ISSUE TITLE
Monitoreo del modelo

### ISSUE THREAD

**Issue by codeMariana** [santibatte/dpa_2021#155]
- [ ] Dashboard creation using Dash. @carlosgeovany 
- [x] Output in RDS.

**Lo que se entrega:**

- [ ] Dashboard en dash de al menos la distribución de scores del modelo seleccionado en el último punto en el tiempo con el que fue validado y la distribución obtenida para las últimas predicciones (último consecutivo). @carlosgeovany 

**Lo que se muestra en la DEMO:**

- [ ] Mostrar el monitoreo del modelo (port forwarding EC2) con histograma de scores de predicción del modelo.

**Comment by santibatte** [comment]
Completado
