### ISSUE TITLE
Completar README.md

### ISSUE THREAD

**Issue by codeMariana** [santibatte/dpa_2021#3]
README.md
- [x] Integrantes del equipo.
- [x] Summary de los datos con los que trabajarás:
      - [ x ] Número de registros.
      - [ x] Número de columnas.
      - [ x ] Qué variables son, qué información tienen.
- [x] Pregunta analítica a contestar con el modelo predictivo.
- [x] Frecuencia de actualización de los datos.

**Comment by santibatte** [comment]
Se agrego la pregunta analitica.
