### ISSUE TITLE
Aequitas Analysis

### ISSUE THREAD

**Issue by codeMariana** [santibatte/dpa_2021#41]
### Objetivo

1. Obtener todos los parámetros relacionados con sesgo y equidad relacionados con el modelo entrenado

### Módulos

- `pipeline/bias_fairness.py`: evaluar métricas de equidad del modelo

### To do's
- [ ] Deliver dataframe with
    - [ ] unique id
    - [ ] prediction labels
    - [ ] real labels
    - [ ] reference group

**Comment by robperch** [comment]
This issue is duplicated... see #132
