### ISSUE TITLE
Create unit test luigi tasks and rename luigi files

### ISSUE THREAD

**Issue by robperch** [santibatte/dpa_2021#88]
# To-do's
- [x] Add prefix "#_luigi_" to all files

# Notes
- "#" refers to a number that relates with the task's order in the pipeline

**Comment by santibatte** [comment]
We are going to start .py luigi tasks with letters (a,b,c,d...) as using numbers is no good practice in Linux

**Comment by santibatte** [comment]
Agregue aqui lo de crear unit tests tasks porque no tiene sentido hacerlo en dos veces...

**Comment by robperch** [comment]
@santibatte I think that the unit tests don't requiere metadata. The only function of the unit tests is to stop the pipeline if something isn't working as intended.

--edit: forget it... I think you're right... we should store unit-test metadata in RDS.
