### ISSUE TITLE
Understand how we'll have to run the pipeline in class

### ISSUE THREAD

**Issue by robperch** [santibatte/dpa_2021#90]
# Questions
1. ¿Are we going to be asked to run each task independently? (e.g. only Transformation, only Feature Engineering).

**Comment by codeMariana** [comment]
Para la presentación en clase se revisará:

1. Correr preprocesamiento y limpieza "nuevo" -> luigi corre
- Se muestra que se generan los metadatos de preprocesamiento y limpieza en la base de datos
- Se muestra la salida del preprocesamiento y limpieza (S3 o RDS)
- Mostrar DAG en verde

2. Correr preprocesamiento y limpieza "repetido" -> luigi no corre nada nuevo
- Se muestra que no se generaron los metadatos de preprocesamiento y limpieza en la base de datos
- Se muestra que no se genera nueva salida del preprocesamiento y limpieza (S3 o RDS)

3. Correr task de feature engineering (FE) "nuevo" -> luigi corre
- Se muestra que se generan los metadatos de FE en la base de datos
- Se muestra la salida del feature engineering (s3 o RDS)
- Se muestra DAG en verde

4. Correr task de feature engineering (FE) "repetido" -> luigi no corre nada nuevo
- Se muestra que no se generan los metadatos de FE en la base de datos
- Se muestra que no se genera nueva salida del FE (S3 o RDS)

**Comment by codeMariana** [comment]
Se atienden comentarios y Santi presenta.
